[package]
name = "boardgame2"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"
rand = "0.8.5"

[profile.release]
debug = true
